import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Market place',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className='bg-fixed flex items-center justify-center h-full'>
        <div className="bg-white overflow-auto w-96 h-screen ">
          {children}
        </div>
      </body>
    </html>
  );
}
